version: '3.4'
services:
  
  api:
    restart: always
    build: ./api
    container_name: api 
    ports:
      - "5005:5005" 
    networks:
      fictizia:
        ipv4_address: 172.18.1.5
        
networks:
  fictizia:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
