version: '3.4'

services:
  kafka:
    restart: always
    container_name: kafka    
    image: 'spotify/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
      - '2181:2181'
    volumes:
      - ./kafka-logs:/tmp/kafka-logs
    environment: 
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=172.20.1.3
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.3   

  manager-kafka:
    restart: always
    container_name: kafka-manager    
    image: 'sheepkiller/kafka-manager:latest'
    hostname: kafka-manager
    ports:
      - '9000:9000'
    environment:
      - ZK_HOSTS=172.20.1.3:2181
      - APPLICATION_SECRET=letmein
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.4  

  producer:
    restart: on-failure
    container_name: producer    
    build: ./producer
    hostname: producer
    depends_on:
      - kafka
    environment:
      - KAFKA_PORT=9092
      - KAFKA_HOST=172.20.1.3      
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.5   
        
  consumer:
    restart: always
    container_name: consumer    
    build: ./consumer
    hostname: consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_PORT=9092
      - KAFKA_HOST=172.20.1.3
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.6 

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo_db  
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/data/db
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.7

  mongo_api:
    restart: always
    build: ./api
    container_name: mongo_api 
    ports:
      - "5005:5005"
    environment:
      - DATABASE_PORT=27017
      - DATABASE_HOST=172.20.1.7
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.8

  producer_dates:
    restart: on-failure
    container_name: producer_dates    
    build: ./date-producer
    hostname: producer_dates
    depends_on:
      - kafka
    environment:
      - KAFKA_PORT=9092
      - KAFKA_HOST=172.20.1.3      
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.9  

networks:
  fictizia_kafka:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
