version: '3.4'

services:
  kafka:
    restart: always
    container_name: kafka    
    image: 'spotify/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
      - '2181:2181'
    volumes:
      - ./kafka-logs:/tmp/kafka-logs
    environment: 
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=localhost
    networks:
      fictizia_kafka:
        ipv4_address: 172.20.1.3

networks:
  fictizia_kafka:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
